#!/bin/sh

# Edit this line with the path to your configuration file
# You'll have to update last_update field there when we get more updates so you
# only get the "critical" status when there's a new one
CONFIG=$(cat ~/Doc/astro-contrib.json)

CAMPAIGN_ID=$(echo $CONFIG | jq -r '.campaign_id')
CAMPAIGN_SLUG=$(echo $CONFIG | jq -r '.campaign_slug')
LAST_UPDATE=$(echo $CONFIG | jq -r '.last_update')
USER_ID=$(echo $CONFIG | jq -r '.user_id')
COOKIE=$(echo $CONFIG | jq -r '.cookie')

UPDATES=$(curl -s "https://www.indiegogo.com/private_api/campaigns/$CAMPAIGN_ID/updates?page=1" \
  -H "authority: www.indiegogo.com" \
  -H "pragma: no-cache" \
  -H "cache-control: no-cache" \
  -H 'sec-ch-ua: "Chromium";v="98", " Not A;Brand";v="99"' \
  -H "accept: application/json, text/plain, */*" \
  -H "dnt: 1" \
  -H "sec-ch-ua-mobile: ?0" \
  -H "user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.121 Safari/537.36" \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H "sec-fetch-site: same-origin" \
  -H "sec-fetch-mode: cors" \
  -H "sec-fetch-dest: empty" \
  -H "referer: https://www.indiegogo.com/projects/$CAMPAIGN_SLUG/x/$USER_ID" \
  -H "accept-language: en-US,en;q=0.9" \
  -H "cookie: $COOKIE" \
  --compressed \
  | jq -r '.pagination.count')

if [ "$UPDATES" -gt "$LAST_UPDATE" ]; then
  STATUS="Critical"
else
  STATUS="Info"
fi

# Json format used by i3status-rust
# Make your own if you have different needs
echo "{\"state\": \"$STATUS\", \"text\": \"Astro: $UPDATES updates\"}"
