#!/bin/bash
# Periodically check in on the status of an indiegogo contribution.

# Where to save the output.
FILE=~/Documents/iggStatus

# Delays in seconds.
BASE_DELAY=1500 # Keep this large.
MAX_RANDOM_DELAY=600 # This is an additional random delay so that it looks less like a bot.

# Quick reference:
#   seconds   minutes   hours
#   300       5
#   600       10
#   900       15
#   1200      20
#   1500      25
#   1800      30
#   2100      35
#   2400      40
#   2700      45
#   3000      50
#   3300      55
#   3600                1
#   7200                2
#   10800               3
#   14400               4

while true; do
  DELAY=$(($BASE_DELAY + $RANDOM % $MAX_RANDOM_DELAY))
  NEXT_UPDATE=$(($(date +%s) + $DELAY))
  echo "Last update: $(date)" > "$FILE"
  echo "Next update: $(date --date="@$NEXT_UPDATE") ($DELAY)" >> "$FILE"
  echo "Status:      $(iggStatus)" >> "$FILE"
  
  sleep "$DELAY"
done 
